<a href="https://colab.research.google.com/github/Henil21/Mental_health_NLP/blob/main/Mental_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
Data=pd.read_csv('/content/drive/MyDrive/mental_health.csv')
Data.count()

text     27977
label    27977
dtype: int64

In [3]:
text=Data['text']
label=Data['label']
label.value_counts()


0    14139
1    13838
Name: label, dtype: int64

In [4]:
train_shf=Data.sample(frac=1,random_state=42)
train_shf.head()

text  label
6604   im ready gothanks previous person commented la...      1
25912  atoms ashim posting im anonymous molested  old...      1
18308  wanna use omegle cus self esteems low ppl alwa...      0
18875  hey world questioni curious think lot people r...      1
23181  guuuuuys passed dance exams honors got honors ...      0

In [5]:
# lets visualize some random training example
import random
random_index=random.randint(0, len(train_shf)-5)
# create random index not higher than total number of samples
for row in train_shf[["text","label"]][random_index:random_index+5].itertuples():
  _,text,label=row
  print(f"label:{label}","(mental health abnormal)" if label>0 else "(normal)")
  print(f"Text:\n{text}\n")
  print("--------\n")

label:0 (normal)
Text:
get chest back  used baby sat nanas neighbour sister whos younger me would play kids years older us always picked me neighbour  daughters son son nice daughters werent oldest one would push sister snow walking place finally enough told pushed sister snow would hit her went said pushed really hard snow also   got back house told mom got trouble crying trying explain really happened fell deaf ears mom told stop crying shell give something cry grabbed arm really hard shoved living room even worse part sister outside playing daughters pop trailer if know please google it trailer drive way super hot day summer opening storage compartments look inside one them super hot could barely breath head also dark inside see arms well feeling something bad going happen put hands edge could push it  girls wanted put storage compartment feeling going leave die sister watching anything basically grabbed tried shove somehow able push back get free shoved ground really hard scared  s

In [6]:
from sklearn.model_selection import train_test_split

train_sentences,val_sentences,train_labels,val_labels=train_test_split(Data["text"].to_numpy(),
                                                                       Data["label"].to_numpy(),
                                                                       test_size=0.3,
                                                                       random_state=42)


In [7]:
train_sentences[:10]

array(['silly putty implies serious putty',
       'literally sat bed crying begging someone something kill lmaoi feel fuckin trapped mani one want worry shit thanks reading guess method  would done tonight',
       'lot delayed this im doneim sorry thank kind words cant keep anymore cant',
       'im going  hours get worki couldnt get much sleep thing going head wanna die wanna die wanna die over could succeeded six redflag attempts ive made past year',
       'hi help guy told would put blenderleave blended mean',
       'plop join fast among us ehejidjdjdjdjdjdidjdjddjd dbbd',
       'perfect man alive  correct answer kim taehyung',
       'happy wife happy life haha kidding ill never happy life wife miserable ha joshin you im gay',
       'racist anything racist fuck marathons like bruh cmon aint one got need god damn marathon',
       'yeahi really much left except alcohol absolutly one life turn times like this always anyone else world remember things tell them im rational want c

In [8]:
val_sentences[:10]

array(['im ready gothanks previous person commented last post pushing edge mum work tomorrow thursday friday thats ill it creating set tomorrow week nothing ever goes way life ive ruined childhood trauma effects life result abandoned everybody ive ever loved even change heart still need go current situation thats it im going die soon',
       'atoms ashim posting im anonymous molested  older sister cover secret played liar entire childhood put bad spot emotionally constantly getting trouble parents school bullied rediculed friends harrassed elementary school students teachers put medication rd grade everyday pulled classroom sit principal office would come home crying everyday mistreatment mom finally enough pulled public school transferred private christian school behind education next year retake rd grade students bullied started fight back aggressively also landed principals office th grade transferred back public school made friends bullies bad kids class want bullied anymore tough

In [9]:
# find the average number of token(words) in the training tweet
# Find average number of tokens (words) in training Tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

72

In [10]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

# Setup text vectorization with custom variables
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 72 # max length our sequences will be (e.g. how many words from a Tweet does our model see?)

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                     split="whitespace",
                                    output_mode="int",
                                    output_sequence_length=max_length)


In [11]:
text_vectorizer.adapt(train_sentences)
sample_text='this is stupid someone kill me fuck'
text_vectorizer([sample_text])

<tf.Tensor: shape=(1, 72), dtype=int64, numpy=
array([[ 68, 256, 252,  40,  69,  10, 124,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0]])>

In [12]:
import random
random_sentence=random.choice(train_sentences)
random_sentence
print(f'orignal text is\n {random_sentence} \n\n and the vectorized text is \n {text_vectorizer([random_sentence])}')

orignal text is
 want attention want heart maybe hate thought someone newlala 

 and the vectorized text is 
 [[  4 493   4 333 119  79  85  40   1   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


In [13]:
words_in_voc=text_vectorizer.get_vocabulary()
top_5=words_in_voc[:5]
bottom_5=words_in_voc[-5:]
print(f"number of word in vocab {len(words_in_voc)}\n")
print(f"5 most comman word in  vocab {top_5}\n")
print(f"5 least comman  word in vocab {bottom_5}")


number of word in vocab 10000

5 most comman word in  vocab ['', '[UNK]', 'im', 'like', 'want']

5 least comman  word in vocab ['botched', 'bosses', 'boomers', 'boo', 'boiled']


In [14]:
from tensorflow.keras import layers
embedding = layers.Embedding(input_dim=max_vocab_length,#set the input shape
                             output_dim=128,
                             input_length=max_length)

In [15]:
# Convert text into number
from sklearn.feature_extraction.text import TfidfVectorizer
# our model
from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline

# create tokenization and modelling pipeline
model_0 = Pipeline([
    ("tfidf",TfidfVectorizer()),# convert words to number using tfidf
    ("clf",MultinomialNB())# model the text
])
# fit the pipleine to the training data
model_0.fit(train_sentences,train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [16]:
baseline_score=model_0.score(val_sentences,val_labels)
# as we use .evaluate in tf for sklearn its .score
baseline_score*100

83.50011913271385

In [17]:
from sklearn.metrics import accuracy_score,precision_recall_fscore_support
def calculate_results(y_true,y_pred):
  # Calculate model accuracy
  model_accuracy=accuracy_score(y_true,y_pred)*100
  # Calculate model precision, recall and f1 score using "weighted" average
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                   "precision":model_precision*100,
                   "recall":model_recall*100,
                   "f1":model_f1*100
                   }
  return model_results

In [18]:
from tensorflow.keras import layers
import tensorflow as tf
tf.random.set_seed(42)
inputs=layers.Input(shape=(1,),dtype="string")
x=text_vectorizer(inputs)
x=embedding(x)
x=layers.Bidirectional(layers.LSTM(64,return_sequences=True))(x) #layers.Bidirectional works with any LSTM
# print(x.shape)
x=layers.Bidirectional(layers.GRU(64))(x)
outputs=layers.Dense(1,activation="sigmoid")(x)
model_4=tf.keras.Model(inputs,outputs,name="model_4_bidirectional")

In [19]:
# Compile model
model_4.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

In [20]:
# Fit the model
model_4_history=model_4.fit(train_sentences,
                            train_labels,
                            epochs=5,
                            validation_data=(val_sentences,val_labels))

Epoch 1/5
612/612 [==============================] - 89s 117ms/step - loss: 0.2518 - accuracy: 0.8938 - val_loss: 0.2017 - val_accuracy: 0.9189
Epoch 2/5
612/612 [==============================] - 26s 42ms/step - loss: 0.1250 - accuracy: 0.9545 - val_loss: 0.2119 - val_accuracy: 0.9202
Epoch 3/5
612/612 [==============================] - 17s 28ms/step - loss: 0.0690 - accuracy: 0.9749 - val_loss: 0.2382 - val_accuracy: 0.9159
Epoch 4/5
612/612 [==============================] - 15s 25ms/step - loss: 0.0416 - accuracy: 0.9854 - val_loss: 0.2868 - val_accuracy: 0.9137
Epoch 5/5
612/612 [==============================] - 15s 25ms/step - loss: 0.0346 - accuracy: 0.9875 - val_loss: 0.3067 - val_accuracy: 0.9107


In [21]:
y_pred=model_4.predict(val_sentences)
y_pred[:10]

263/263 [==============================] - 4s 8ms/step


array([[9.9950039e-01],
       [9.9604404e-01],
       [4.9021109e-03],
       [9.9912971e-01],
       [2.7716402e-03],
       [9.3329275e-01],
       [9.9869126e-01],
       [9.9926883e-01],
       [9.6959811e-01],
       [9.7688855e-05]], dtype=float32)

In [22]:
model_preds=tf.squeeze(tf.round(y_pred))
model_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 0., 1., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [23]:
calculate_results(y_true=val_labels,
                            y_pred=model_preds)

{'accuracy': 91.0650464617584,
 'precision': 91.11975268320376,
 'recall': 91.0650464617584,
 'f1': 91.06559428904863}

In [36]:
import numpy as np
import math
text_s=["In the shadows of my desolate room, I find myself lost in the haunting corridors of my mind. Memories of a time long gone echo through the hollow chambers of my heart, their melancholic melodies a constant reminder of the greatness that once filled my life"]
txt=np.array(text_s)
y_pred=model_4.predict(txt)
# model_preds=tf.squeeze(tf.round(y_pred))
print(int(tf.round(y_pred)))
model_4.evaluate(txt)

1/1 [==============================] - 0s 28ms/step
1
1/1 [==============================] - 0s 29ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00


[0.0, 0.0]